# Generated by Django 4.1.3 on 2022-12-30 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ToDo", "0005_todo_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="description",
        ),
    ]
