# Generated by Django 4.1.3 on 2022-12-29 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ToDo", "0003_alter_todo_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="description",
        ),
    ]
