# Generated by Django 4.1.3 on 2022-12-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ToDo", "0004_remove_todo_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="description",
            field=models.TextField(blank=True, default="None", null=True),
        ),
    ]
